
const $=id=>document.getElementById(id),C=$('board'),X=C.getContext('2d');
const W=10,H=20,FALL=760,TYPES=['I','J','L','O','S','T','Z'];
const SH={I:[[1,1,1,1]],J:[[1,0,0],[1,1,1]],L:[[0,0,1],[1,1,1]],O:[[1,1],[1,1]],S:[[0,1,1],[1,1,0]],T:[[0,1,0],[1,1,1]],Z:[[1,1,0],[0,1,1]]};
const colors=['#55d8ff','#5f7cff','#ff9f43','#ffd166','#66e39a','#d47aff','#ff5c8a'];
let b=board(),cur=null,score=0,lines=0,level=1,combo=0,interval=FALL,last=0,run=false,paused=false,rng=Math.random,seed=1,mode='single',room='',me='',ws=null,players=new Map(),lastSend=0,touch={x:0,y:0},clearFx=[],shake=0,waitingLock=false,teamScore=0,teamLines=0,teamCombo=0,teamLevel=1,round=1,gameToken=0,downHeld=false,downTimer=0;
function board(){return Array.from({length:H},()=>Array(W).fill(0))} function mulberry(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}} function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function scene(id){document.querySelectorAll('.scene').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function resize(){const d=Math.min(devicePixelRatio||1,2),w=C.clientWidth,h=C.clientHeight;C.width=Math.max(1,w*d);C.height=Math.max(1,h*d);X.setTransform(d,0,0,d,0,0);draw()} window.addEventListener('resize',resize);
function hit(m,x,y,base=b){for(let r=0;r<m.length;r++)for(let c=0;c<m[r].length;c++)if(m[r][c]){const xx=x+c,yy=y+r;if(xx<0||xx>=W||yy>=H||(yy>=0&&base[yy][xx]))return true}return false}
function spawn(index=null){const i=index==null?Math.floor(rng()*7):index%7,m=SH[TYPES[i]].map(r=>r.slice());cur={m,x:Math.floor((W-m[0].length)/2),y:0,c:i,type:TYPES[i],rot:0};waitingLock=false;if(hit(m,cur.x,0)){endGame();return false}return true}
function startGame(s=Math.floor(Math.random()*2147483647),roundNo=1,initialPiece=null){gameToken++;seed=s;round=roundNo;rng=mulberry(seed+roundNo);b=board();score=lines=combo=0;level=1;interval=FALL;teamScore=teamLines=teamCombo=0;teamLevel=1;run=true;paused=false;waitingLock=false;clearFx=[];shake=0;applyTheme();spawn(initialPiece);stats();hideOverlay();$('pauseMenu').classList.add('hidden');$('gameModeLabel').textContent=mode==='single'?'Single Player':mode==='coop'?`🤝 Co-op • Room ${room}`:`⚔️ Versus • Room ${room}`;last=performance.now();requestAnimationFrame(loop)}
function move(dx,dy){if(!run||paused||waitingLock)return false;if(!hit(cur.m,cur.x+dx,cur.y+dy)){cur.x+=dx;cur.y+=dy;return true}return false}
function rotate(){if(!run||paused||waitingLock)return;const n=cur.m[0].map((_,i)=>cur.m.map(r=>r[i]).reverse());for(const k of [0,-1,1,-2,2])if(!hit(n,cur.x+k,cur.y)){cur.m=n;cur.x+=k;cur.rot=(cur.rot+1)%4;return}}
function lock(){if(!run||paused||waitingLock)return;if(mode==='coop'&&room){waitingLock=true;send({type:'coopLock',x:cur.x,y:cur.y,matrix:cur.m,c:cur.c,player:me,round});return}for(let r=0;r<cur.m.length;r++)for(let c=0;c<cur.m[r].length;c++)if(cur.m[r][c]&&cur.y+r>=0)b[cur.y+r][cur.x+c]=cur.c+1;clearLines();spawn()}
function clearLines(){const rows=[];for(let r=0;r<H;r++)if(b[r].every(Boolean))rows.push(r);if(!rows.length){combo=0;stats();return}const survivors=b.filter((_,r)=>!rows.includes(r));while(survivors.length<H)survivors.unshift(Array(W).fill(0));b=survivors;const n=rows.length;baseScore(n);showPraise(n);showScorePop(`+${score.toLocaleString()}${combo>1?' • COMBO ×'+combo:''}`);fx(rows)}
function baseScore(n){const base=[0,100,300,500,800][n]||1200;combo++;lines+=n;const oldLevel=level;level=1+Math.floor(lines/10);interval=Math.max(80,FALL-(level-1)*65);const comboBonus=Math.min(combo,12)*75;const lineBonus=base*level;score+=lineBonus+comboBonus;stats();if(level>oldLevel)levelTransition(level)}
function fx(rows){shake=Math.min(16,5+rows.length*3);clearFx.push({rows,age:0,duration:380})}
function levelTransition(n){applyTheme();showRoundBanner(`LEVEL ${n} • NEW THEME`);$('boardPanel').classList.remove('levelShift');void $('boardPanel').offsetWidth;$('boardPanel').classList.add('levelShift');if(mode==='coop')send({type:'level',level:n,round})}
function applyTheme(){const k=Math.min(5,1+Math.floor((level-1)/3));document.documentElement.classList.remove('theme2','theme3','theme4','theme5');if(k>1)document.documentElement.classList.add('theme'+k)}
function hard(){if(!run||paused||waitingLock)return;let d=0;while(move(0,1))d++;if(mode!=='coop'){score+=d*2;stats()}lock()}
function stats(){if(mode==='coop'){$('score').textContent=teamScore.toLocaleString();$('lines').textContent=teamLines;$('level').textContent=teamLevel;$('combo').textContent=teamCombo}else{$('score').textContent=score.toLocaleString();$('lines').textContent=lines;$('level').textContent=level;$('combo').textContent=combo}}
function showScorePop(t){const e=document.createElement('div');e.className='scorePop';e.textContent=t;$('boardPanel').appendChild(e);setTimeout(()=>e.remove(),900)}
function showPraise(n){const words=['NICE CLEAR!','GREAT DOUBLE!','AMAZING TRIPLE!','STRAWBERRY LEGEND!'];showRoundBanner(words[Math.min(n-1,3)]+' '+(combo>1?'COMBO!':''))}
function showRoundBanner(t){const e=document.createElement('div');e.className='roundBanner';e.textContent=t;$('boardPanel').appendChild(e);setTimeout(()=>e.remove(),1200)}
function endGame(){if(!run)return;run=false;sendState();if(room)send({type:'roundEnd',score,round});const finalScore=mode==='coop'?teamScore:score;const finalLines=mode==='coop'?teamLines:lines;showOverlay('Level End',`Round ${round} complete • Score ${finalScore.toLocaleString()} • ${finalLines} lines`,mode==='single'?'Play Again':'Ready for Next Round',mode==='single'?()=>startGame():()=>send({type:'nextRound'}))}
function loop(t){if(!run||paused)return;const dt=t-last;if(dt>=interval){if(!move(0,1))lock();last=t}if(downHeld&&t-downTimer>35){if(move(0,1)){if(mode!=='coop')score++;stats()}downTimer=t}draw();if(t-lastSend>100){lastSend=t;sendState()}if(shake>0)shake=Math.max(0,shake-.7);requestAnimationFrame(loop)}
function draw(){const bw=C.clientWidth/W,bh=C.clientHeight/H;X.save();if(shake)X.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);X.clearRect(-20,-20,C.clientWidth+40,C.clientHeight+40);const g=X.createLinearGradient(0,0,0,C.clientHeight);g.addColorStop(0,'#111733');g.addColorStop(1,'#080b17');X.fillStyle=g;X.fillRect(0,0,C.clientWidth,C.clientHeight);X.strokeStyle='#202848';for(let x=1;x<W;x++){X.beginPath();X.moveTo(x*bw,0);X.lineTo(x*bw,C.clientHeight);X.stroke()}for(let y=1;y<H;y++){X.beginPath();X.moveTo(0,y*bh);X.lineTo(C.clientWidth,y*bh);X.stroke()}if(b)for(let r=0;r<H;r++)for(let c=0;c<W;c++)if(b[r][c])cell(c,r,b[r][c]-1,1);if(cur&&!waitingLock){let gy=cur.y;while(!hit(cur.m,cur.x,gy+1))gy++;for(let r=0;r<cur.m.length;r++)for(let c=0;c<cur.m[r].length;c++)if(cur.m[r][c]&&gy+r>=0)cell(cur.x+c,gy+r,cur.c,.18);for(let r=0;r<cur.m.length;r++)for(let c=0;c<cur.m[r].length;c++)if(cur.m[r][c]&&cur.y+r>=0)cell(cur.x+c,cur.y+r,cur.c,1)}for(const fx of clearFx){fx.age+=16;const p=Math.min(1,fx.age/fx.duration);X.globalAlpha=(1-p)*.75;for(const r of fx.rows){X.fillStyle='#fff';X.fillRect(0,r*bh,C.clientWidth,bh)}X.globalAlpha=1}clearFx=clearFx.filter(f=>f.age<f.duration);X.restore()}
function cell(c,r,i,a){X.globalAlpha=a;X.fillStyle=colors[i]||'#fff';X.fillRect(c*C.clientWidth/W+1,r*C.clientHeight/H+1,C.clientWidth/W-2,C.clientHeight/H-2);X.globalAlpha=1}
function drawRemote(p){const c=document.querySelector(`canvas[data-id="${p.id}"]`);if(!c)return;const d=Math.min(devicePixelRatio||1,2),w=c.clientWidth,h=c.clientHeight;c.width=Math.max(1,w*d);c.height=Math.max(1,h*d);const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.fillStyle='#14070d';x.fillRect(0,0,w,h);if(!p.board)return;const bw=w/W,bh=h/H;for(let r=0;r<H;r++)for(let j=0;j<W;j++)if(p.board[r]?.[j]){x.fillStyle=colors[p.board[r][j]-1]||'#fff';x.fillRect(j*bw+1,r*bh+1,bw-2,bh-2)}if(p.active?.m){const a=p.active;for(let r=0;r<a.m.length;r++)for(let j=0;j<a.m[r].length;j++)if(a.m[r][j]){x.globalAlpha=.55;x.fillStyle=colors[a.c]||'#fff';x.fillRect((a.x+j)*bw+1,(a.y+r)*bh+1,bw-2,bh-2);x.globalAlpha=1}}}
function renderPlayers(){const arr=[...players.values()];$('playersView').innerHTML=mode==='single'?'Solo':arr.map(p=>`<div class="player"><div><b>${esc(p.name)}${p.id===me?' (you)':''}</b><div class="mini">${Number(p.score||0).toLocaleString()} pts${p.alive===false?' • OUT':''}</div></div><div class="${p.ready?'ready':'wait'}">${p.ready?'READY':'WAIT'}</div></div>`).join('');if(mode==='single'){$('remote').innerHTML='';return}$('remote').innerHTML=arr.filter(p=>p.id!==me).map(p=>`<div class="remoteCard"><canvas class="remoteCanvas" data-id="${p.id}"></canvas><div class="remoteName">${esc(p.name)}</div></div>`).join('');arr.filter(p=>p.id!==me).forEach(drawRemote)}
function renderLobbies(list){const el=$('lobbyList');if(!list.length){el.innerHTML='<div class="mini">No open rooms yet — create one.</div>';return}el.innerHTML=list.map(r=>`<div class="lobbyItem" data-code="${r.code}"><b>${r.code} · ${r.mode==='coop'?'🤝 Co-op':'⚔️ Versus'}</b><span>${r.players}/${r.maxPlayers} players · waiting</span></div>`).join('');el.querySelectorAll('.lobbyItem').forEach(x=>x.onclick=()=>joinRoom(x.dataset.code))}
function send(m){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(m))}function requestLobbies(){send({type:'lobbies'})}function setStatus(t){$('roomText').textContent=t;$('roomNet').textContent=t}
function createRoom(){send({type:'createRoom',name:$('name').value.trim()||'Player',mode:$('mode').value})}function joinRoom(c){const n=$('name').value.trim()||'Player';if(!c)return setStatus('Enter a room code.');send({type:'joinRoom',name:n,code:c})}
function showRoomLobby(){scene('roomScene');requestLobbies();setStatus(room?`Room ${room} • waiting for everyone to Ready.`:'Create or join a room to start.')}
function leaveToHome(msg){send({type:'leave'});room='';mode='single';players.clear();b=board();cur=null;run=false;paused=false;scene('homeScene');$('homeNet').textContent=msg||'Back at Home.';requestLobbies()}
function showOverlay(t,p,bt,fn){$('ovTitle').textContent=t;$('ovText').textContent=p;$('ovBtn').textContent=bt;$('ovBtn').onclick=fn;$('overlay').classList.remove('hidden')}
function hideOverlay(){$('overlay').classList.add('hidden')}
function togglePause(){if(!run)return;paused=!paused;$('pauseMenu').classList.toggle('hidden',!paused);if(!paused){last=performance.now();requestAnimationFrame(loop)}draw()}
function action(a){if(a==='left')move(-1,0);if(a==='right')move(1,0);if(a==='down'){downHeld=true;downTimer=performance.now();if(move(0,1)&&mode!=='coop'){score++;stats()}}if(a==='rotate')rotate();if(a==='drop')hard();if(a==='pause')togglePause();draw()}
function connect(){const proto=location.protocol==='https:'?'wss':'ws';try{ws=new WebSocket(`${proto}://${location.host}`)}catch{return}ws.onopen=()=>{$('homeNet').textContent='🟢 Live multiplayer connected';$('roomNet').textContent='🟢 LIVE';requestLobbies()};ws.onclose=()=>{$('homeNet').textContent='⚪ Multiplayer offline — single player still works';$('roomNet').textContent='OFFLINE'};ws.onmessage=e=>{try{handle(JSON.parse(e.data))}catch(err){console.error(err)}}}
function handle(m){if(m.type==='hello'){me=m.id;return}if(m.type==='error'){setStatus('⚠️ '+m.message);return}if(m.type==='lobbies'){renderLobbies(m.rooms||[]);$('lobbyUpdated').textContent='Live';return}if(m.type==='joined'){room=m.room;mode=m.mode;$('mode').value=mode;$('roomLabel').textContent=room;$('roomTitle').textContent=`${mode==='coop'?'🤝 Co-op':'⚔️ Versus'} Room ${room}`;setStatus('Room is open. Share the code and wait for everyone to Ready.');scene('roomScene');return}if(m.type==='roomState'){players.clear();(m.players||[]).forEach(p=>players.set(p.id,p));teamScore=m.teamScore||0;teamLines=m.teamLines||0;teamCombo=m.teamCombo||0;teamLevel=m.teamLevel||1;round=m.round||round;renderPlayers();stats();return}if(m.type==='start'){round=m.round||1;scene('gameScene');showOverlay(mode==='coop'?'🤝 Team Start':'⚔️ Match Start',mode==='coop'?'Shared board is synchronized for everyone.':'Compete on your own board.','GO!',()=>startGame(m.seed,round,m.nextPiece));setTimeout(()=>{if(!$('overlay').classList.contains('hidden'))startGame(m.seed,round,m.nextPiece)},900);return}if(m.type==='roundStart'){round=m.round;scene('gameScene');startGame(m.seed,round,m.nextPiece);return}if(m.type==='coopState'){if(Number(m.round)!==round)return;b=(m.board||board()).map(row=>row.slice());teamScore=Number(m.score)||0;teamLines=Number(m.lines)||0;teamCombo=Number(m.combo)||0;teamLevel=Number(m.level)||1;waitingLock=false;applyTheme();if(m.rows?.length){fx(m.rows);showPraise(m.rows.length)}if(m.by&&m.by!==me)showRoundBanner(`${esc(m.byName||'Teammate')} PLACED A BLOCK!`);spawn(m.nextPiece);stats();draw();return}if(m.type==='playerState'&&m.id!==me){players.set(m.id,{...(players.get(m.id)||{}),...m});renderPlayers();return}if(m.type==='roundEnd'){run=false;paused=false;waitingLock=false;$('pauseMenu').classList.add('hidden');const finalScore=mode==='coop'?teamScore:score;const finalLines=mode==='coop'?teamLines:lines;showOverlay('Level End',`Round ${m.round} ended • Score ${Number(finalScore||0).toLocaleString()} • ${Number(finalLines||0)} lines`,'Ready for Next Round',()=>send({type:'nextRound'}));return}if(m.type==='gameEvent')return;if(m.type==='roomExpired')leaveToHome('Room expired because nobody was active.')}
$('homeSingle').onclick=()=>{mode='single';scene('gameScene');startGame()};$('homeRooms').onclick=showRoomLobby;$('create').onclick=createRoom;$('join').onclick=()=>joinRoom($('room').value.trim());$('ready').onclick=()=>{if(!room)return setStatus('Create or join a room first.');const p=players.get(me);send({type:'setReady',ready:!(p?.ready)})};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(room);setStatus('Room code copied!')}catch{setStatus('Room code: '+room)}};$('leaveRoom').onclick=()=>leaveToHome('You left the room.');$('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;$('pauseHome').onclick=()=>leaveToHome('Back at Home.');
document.querySelectorAll('[data-a]').forEach(el=>{el.addEventListener('pointerdown',e=>{e.preventDefault();action(el.dataset.a)});el.addEventListener('pointerup',()=>{if(el.dataset.a==='down')downHeld=false});el.addEventListener('pointercancel',()=>{if(el.dataset.a==='down')downHeld=false});el.addEventListener('pointerleave',()=>{if(el.dataset.a==='down')downHeld=false})});
window.addEventListener('keydown',e=>{if(e.repeat&&e.key!=='ArrowDown')return;if(e.key==='ArrowDown'){e.preventDefault();downHeld=true;action('down');return}const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'rotate',' ':'drop'};if(m[e.key]){e.preventDefault();action(m[e.key])}if(e.key.toLowerCase()==='p')togglePause()});window.addEventListener('keyup',e=>{if(e.key==='ArrowDown')downHeld=false});
C.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY}});C.addEventListener('pointerup',e=>{const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.max(Math.abs(dx),Math.abs(dy))<20)action('rotate');else if(Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left');else action(dy>0?'down':'rotate')});
setInterval(()=>{if(ws?.readyState===WebSocket.OPEN)requestLobbies()},2000);connect();resize();
